### PR TITLE
set up basic CI with Travis

### PR DESCRIPTION
**Pull request by dornheimer**
interestingly, database creation with postgres 10 fails, but works just fine with 9. it looks like travis does not have full support for 10 yet (we probably won't need it anyway).

### CODE REVIEW

**Comment by dornheimer** [comment]
@fspoettel so far, the test are very minimal and would need to be expanded.

* do think you running tests with a postgres db is the right approach? (it doesn't really have any data yet, but i suppose it would need to be populated with mock data or a subset of the corpus)
* what kind of tests are necessary for an app like this?

**Comment by fspoettel** [comment]
> do think you running tests with a postgres db is the right approach? (it doesn't really have any data yet, but i suppose it would need to be populated with mock data or a subset of the corpus)

It depends. The way I see it, a testing database is probably the simpler approach than a `mock` in the long run. Testing with a subset of the corpus would def. allow us to have painless tests for the more complex functionality coming later. It would make sense to swap out postgres for sqlite while testing though to speed it up (if there are no compat. issues)

> what kind of tests are necessary for an app like this?

Running integration tests for the exposed routes is probably the minimum that should be done. We could add unit tests for core logic too.

**Comment by dornheimer** [comment]
@fspoettel tests now run against a subset of the corpus and are using a postgres db. since i am not really familiar with the differences in sqlite and postgres dialects, i think using the real db engine for integration tests makes sense. if we need to test db interaction at the unit level, we could use an in-memory sqlite in these cases.

the test data is just a JSON export from the db that is created from the corpus. this allows use to switch database engines and populate a new db every time the tests run. not sure if there is a more elegant way to do this. time for database setup is about 20s.

**Comment by fspoettel** [comment]
@dornheimer Great work! I agree with the approach here, it's a nice testing env.

**Review by fspoettel — APPROVED** [review]

**Comment by fspoettel** [comment]
Please cherry pick 188133b from #15 onto this branch

**Comment by dornheimer** [comment]
@fspoettel the commit refers to a file that is not in this branch.  `SQLALCHEMY_DATABASE_URI` is correctly set in the main config, but i duplicated the settings and forgot to remove it. i was intending to squash this commit, as it doesn't really do anything.

by default, the `TestingConfig` does not have `ELASTICSEARCH_URL` set, so that normal tests do not need to have the elasticsearch service enabled. the only purpose of the `ES_TestingConfig` is to have ES enabled for these tests specifically.

**Pull request merged**
